.\" DataReel Cluster Manager (DRCM) 1.X Manpage
.\" Copyright (c) 2016 DataReel Software Development
.TH drcm 8 "16 Aug 2016" "1.30" "DataReel Cluster Manager"
.SH NAME
drcm_server \- Start the DRCM service
.SH SYNOPSIS
drcm_server
.SH DESCRIPTION

.SH OPTIONS

.SH SEE ALSO
drcm(8)
.SH BUGS
https://github.com/datareel/datareel/issues
.SH AUTHOR
 DataReel Software Development
