.\" DataReel Cluster Manager (DRCM) 1.X Manpage
.\" Copyright (c) 2016 DataReel Software Development
.TH drcm_server 1 "17 Sep 2016" "1.37" "DataReel Cluster Manager"
.SH NAME
drcm_server --client \- Start the DRCM client for cluster monitoring
.SH SYNOPSIS
drcm_server --client --command=[cm_stat help ping printcfg rstats]
.SH DESCRIPTION
.Nm
The DRCM client is used to check cluster health and for testing. See
drcm(8) for server start up options.
.SH OPTIONS
.TP 
.B Detailed Cluster Status Monitor:
.P
	drcm_server --client --command=cm_stat
.TP
.B Test connectivity to all active cluster nodes:
.P
	drcm_server --client --command=ping
.TP
.B Ping single node by name or IP:
.P
	drcm_server --client --command=ping -n"CMNODE_nodename"
.P
	drcm_server --client --command=ping -n"localhost"
.P
	drcm_server --client --command=ping -n"$(uname -n)"
.TP
.B Ping single and specify a ping count:
.P
 	drcm_server --client --command=ping -c5 -n"$(uname -n)"
.TP
.B Print cluster configuration:
.P
	drcm_server --client --command=printcfg
.TP
.B Print raw stats buffer for each cluster node:
.P
	drcm_server --client --command=rstats
.TP
.B Print raw stats for single node by name or IP:
.P
	drcm_server --client --command=rstats -n"CMNODE_nodename"
.P
	drcm_server --client --command=rstats -n"localhost"
.P
	drcm_server --client --command=rstats -n"$(uname -n)"

.SH SEE ALSO
drcm_server(8)
.SH BUGS
https://github.com/datareel/datareel/issues
.SH AUTHOR
 DataReel Software Development
