.\" DataReel Cluster Manager (DRCM) 1.X Manpage
.\" Copyright (c) 2016 DataReel Software Development
.TH drcm_server 8 "17 Sep 2016" "1.37" "DataReel Cluster Manager"
.SH NAME
drcm_server \- Start the DRCM service
.SH SYNOPSIS
 drcm_server [OPTIONS...]
.SH DESCRIPTION
DataReel cluster manager service.
.SH OPTIONS
.TP
.B args: 
.P
     --help                      Print help message and exit
.P
     --version                   Print version number and exit
.P
     --check-config              Check the CM config file and exit
.P
     --debug                     Enable debug mode default level --debug=1
.P
     --debug-level=1             Set debugging level, 1-5
.P
     --verbose                   Turn on verbose messaging to console
.P
     --verbose-level=1           Set verbose level, 0-5
.P
     --config-file="cm.cfg"      Specify configuration file name
.P
     --log-file="drcm.log"       Specify a log file name
.P
     --log-level=1               Set logging level, 0-5
.P
     --log-file-clear            Clear the log file when program starts
.P
     --log-disable               Disable logging
.TP
.B CM console: 
.P
     --client                    Enter interactive client CM console
.P
     --command="cm_command"      Execute a CM client command and exit
.TP
.B CM console command list: 
.P
     --client --command=help

.SH SEE ALSO
drcm_server(1)
.SH BUGS
https://github.com/datareel/datareel/issues
.SH AUTHOR
 DataReel Software Development
